[build]
  # Build command (not needed for static site)
  command = "echo 'Static site - no build required'"
  
  # Publish directory
  publish = "."

[build.environment]
  # Node version for any future build processes
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache images
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache PDFs
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Force HTTPS redirect
[[redirects]]
  from = "http://gutmandesign.co/*"
  to = "https://gutmandesign.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.gutmandesign.co/*"
  to = "https://gutmandesign.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gutmandesign.co/*"
  to = "https://gutmandesign.co/:splat"
  status = 301
  force = true